version: '3.8'
services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - JWT_SECRET=secret-key

  messaging-service:
    build: ./services/messaging-service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  user-service:
    build: ./services/user-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082